# Generated by Django 2.0.6 on 2018-07-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindb',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
